# See http://about.travis-ci.org/docs/user/build-configuration/
language: scala
scala:
  - 2.10.0
  - 2.10.1
branches:
  only:
    - salat_2.10
notifications:
  email:
    recipients:
      - prasinous@gmail.com
jdk:
  - openjdk7
  - oraclejdk7
  - openjdk6
services:
  - mongodb
